print('\n')
print('Please enter the following information: \n')
print('\n')
first_name = input('First name: ')
last_name = input('Last name: ')
email = input('Email address: ')
phone_number = input('Phone number: ')
job_title = input('Job title: ')
id_number = input('ID number: ')
hair_color = input('Hair color: ')
eye_color = input('Eye color: ')
month_started = input('In which month did you begin employment?: ')
training = input('Have you complete advanced training?(Yes or No): ') 
print('\n')

print('The ID Card is: \n')
print('-----------------------------------')
print(f'{last_name.upper()}, {first_name.title()}')
print(f'{job_title.title()}')
print('ID: ' + id_number)
print('\n')

print(f'{email.lower()}')
print(f'{phone_number}')
print('\n')

print('Hair: ' + hair_color.title() + '         ' + 'Eyes: ' + eye_color.title())
print('Month: ' + month_started.title() + '      ' + 'Training: ' + training.title())
print('------------------------------------')
print('\n')