print('Please enter the following: ')
print('\n')
adjective = input('adjective: ')
animal = input('animal: ')
verb_1 = input('verb: ')
exclamation = input('exclamation: ')
verb_2 = input('verb: ')
verb_3 = input('verb: ')
adjective_2 = input('adjective: ')
noun = input('noun: ')
verb_4 = input('verb: ')
noun_2 = input('plural noun: ')
print('\n')
print('Your story is: ')
print('\n')
print(f'The other day, I was really in trouble. It all started when I saw a very {adjective} {animal} {verb_1} down the hallway. "{exclamation.capitalize()}!" I yelled. But all could think to do was to {verb_2} over and over. Miraculously, that caused it to stop, but not before it tried to {verb_3} right in front of my family. {adjective_2.capitalize()} {noun}s began to {verb_4} down the stairs. Just then, the police showed up with {noun_2} in their hands. ')

